spring:
  redis:
    cluster:
      nodes:
        - 172.28.0.31:6379
        - 172.28.0.32:6379
        - 172.28.0.33:6379
        - 172.28.0.34:6379
        - 172.28.0.35:6379
        - 172.28.0.36:6379
